package visao;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.PersonagemVO;
import servicos.PersonagemServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Douglas
 * @since 07/07/2018 - 3:46
 * @version 1.0 - Beta Carrero
 */
public class GuiCadPersonagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCadSalario
     */
    public GuiCadPersonagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCidade = new javax.swing.ButtonGroup();
        bgSexo = new javax.swing.ButtonGroup();
        bgSimNao = new javax.swing.ButtonGroup();
        bgInsig = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlCidade = new javax.swing.JLabel();
        jrPallet = new javax.swing.JRadioButton();
        jrViridian = new javax.swing.JRadioButton();
        jrPewter = new javax.swing.JRadioButton();
        jrCerulean = new javax.swing.JRadioButton();
        jrSaffron = new javax.swing.JRadioButton();
        jrFuchsia = new javax.swing.JRadioButton();
        jrCinnabar = new javax.swing.JRadioButton();
        jrVermilion = new javax.swing.JRadioButton();
        jrLavender = new javax.swing.JRadioButton();
        jrCeladon = new javax.swing.JRadioButton();
        jlIdade = new javax.swing.JLabel();
        jtIdade = new javax.swing.JTextField();
        jlSexo = new javax.swing.JLabel();
        jrMasc = new javax.swing.JRadioButton();
        jrFemi = new javax.swing.JRadioButton();
        jlInsignia = new javax.swing.JLabel();
        jlCapturado = new javax.swing.JLabel();
        jtCapturado = new javax.swing.JTextField();
        jlSaffari = new javax.swing.JLabel();
        jrSim = new javax.swing.JRadioButton();
        jrNao = new javax.swing.JRadioButton();
        jlNomeErro = new javax.swing.JLabel();
        jlSexoErro = new javax.swing.JLabel();
        jlIdadeErro = new javax.swing.JLabel();
        jlPokemonsErro = new javax.swing.JLabel();
        jrLama = new javax.swing.JRadioButton();
        jrAlma = new javax.swing.JRadioButton();
        jrArcoIris = new javax.swing.JRadioButton();
        jrTerra = new javax.swing.JRadioButton();
        jrRocha = new javax.swing.JRadioButton();
        jrTrovao = new javax.swing.JRadioButton();
        jrVulcao = new javax.swing.JRadioButton();
        jrCascata = new javax.swing.JRadioButton();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jlpDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Personagem"));

        jlNome.setText("Nome Do Personagem:");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jlCidade.setText("Cidade:");

        bgCidade.add(jrPallet);
        jrPallet.setText("Pallet");
        jrPallet.setActionCommand("Pallet");
        jrPallet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrPalletKeyPressed(evt);
            }
        });

        bgCidade.add(jrViridian);
        jrViridian.setText("Viridian");
        jrViridian.setActionCommand("Viridian");
        jrViridian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrViridianKeyPressed(evt);
            }
        });

        bgCidade.add(jrPewter);
        jrPewter.setText("Pewter");
        jrPewter.setActionCommand("Pewter");
        jrPewter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrPewterKeyPressed(evt);
            }
        });

        bgCidade.add(jrCerulean);
        jrCerulean.setText("Cerulean");
        jrCerulean.setActionCommand("Cerulean");
        jrCerulean.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCeruleanKeyPressed(evt);
            }
        });

        bgCidade.add(jrSaffron);
        jrSaffron.setText("Saffron");
        jrSaffron.setActionCommand("Saffron");
        jrSaffron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSaffronKeyPressed(evt);
            }
        });

        bgCidade.add(jrFuchsia);
        jrFuchsia.setText("Fuchsia");
        jrFuchsia.setActionCommand("Fuchsia");

        bgCidade.add(jrCinnabar);
        jrCinnabar.setText("Cinnabar");
        jrCinnabar.setActionCommand("Cinnabar");
        jrCinnabar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCinnabarKeyPressed(evt);
            }
        });

        bgCidade.add(jrVermilion);
        jrVermilion.setText("Vermilion");
        jrVermilion.setActionCommand("Vermilion");
        jrVermilion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrVermilionKeyPressed(evt);
            }
        });

        bgCidade.add(jrLavender);
        jrLavender.setText("Lavender");
        jrLavender.setActionCommand("Lavender");
        jrLavender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrLavenderKeyPressed(evt);
            }
        });

        bgCidade.add(jrCeladon);
        jrCeladon.setText("Celadon");
        jrCeladon.setActionCommand("Celadon");
        jrCeladon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCeladonKeyPressed(evt);
            }
        });

        jlIdade.setText("Idade Personagem:");

        jtIdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtIdadeFocusLost(evt);
            }
        });
        jtIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtIdadeKeyPressed(evt);
            }
        });

        jlSexo.setText("Sexo:");

        bgSexo.add(jrMasc);
        jrMasc.setText("Masculino");
        jrMasc.setActionCommand("Masculino");
        jrMasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMascKeyPressed(evt);
            }
        });

        bgSexo.add(jrFemi);
        jrFemi.setText("Feminino");
        jrFemi.setActionCommand("Feminino");
        jrFemi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemiKeyPressed(evt);
            }
        });

        jlInsignia.setText("Insígnias Conquistadas:");

        jlCapturado.setText("Pokemons Capturados:");

        jtCapturado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCapturadoFocusLost(evt);
            }
        });
        jtCapturado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCapturadoKeyPressed(evt);
            }
        });

        jlSaffari.setText("Acesso Ao Saffari ?");

        bgSimNao.add(jrSim);
        jrSim.setText("Sim");
        jrSim.setActionCommand("Sim");
        jrSim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSimKeyPressed(evt);
            }
        });

        bgSimNao.add(jrNao);
        jrNao.setText("Não");
        jrNao.setActionCommand("Não");
        jrNao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrNaoKeyPressed(evt);
            }
        });

        bgInsig.add(jrLama);
        jrLama.setText("Lama");
        jrLama.setActionCommand("Lama");
        jrLama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrLamaKeyPressed(evt);
            }
        });

        bgInsig.add(jrAlma);
        jrAlma.setText("Alma");
        jrAlma.setActionCommand("Alma");
        jrAlma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrAlmaKeyPressed(evt);
            }
        });

        bgInsig.add(jrArcoIris);
        jrArcoIris.setText("ArcoIris");
        jrArcoIris.setActionCommand("ArcoIris");
        jrArcoIris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrArcoIrisKeyPressed(evt);
            }
        });

        bgInsig.add(jrTerra);
        jrTerra.setText("Terra");
        jrTerra.setActionCommand("Terra");
        jrTerra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrTerraKeyPressed(evt);
            }
        });

        bgInsig.add(jrRocha);
        jrRocha.setText("Rocha");
        jrRocha.setActionCommand("Rocha");
        jrRocha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrRochaKeyPressed(evt);
            }
        });

        bgInsig.add(jrTrovao);
        jrTrovao.setText("Trovão");
        jrTrovao.setActionCommand("Trovão");
        jrTrovao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrTrovaoKeyPressed(evt);
            }
        });

        bgInsig.add(jrVulcao);
        jrVulcao.setText("Vulcão");
        jrVulcao.setActionCommand("Vulcão");
        jrVulcao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrVulcaoKeyPressed(evt);
            }
        });

        bgInsig.add(jrCascata);
        jrCascata.setText("Cascata");
        jrCascata.setActionCommand("Cascata");
        jrCascata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCascataKeyPressed(evt);
            }
        });

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrPallet, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrViridian, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrPewter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrCerulean, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSaffron, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrFuchsia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrCinnabar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrVermilion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrLavender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrCeladon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrMasc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrFemi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlInsignia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCapturado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtCapturado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSaffari, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrNao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSexoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlIdadeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPokemonsErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrLama, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrAlma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrArcoIris, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrTerra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrRocha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrTrovao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrVulcao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrCascata, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrPallet)
                            .addComponent(jrSaffron))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrViridian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrPewter))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrFuchsia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrCinnabar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrCerulean)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrCeladon))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrVermilion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrLavender))))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNomeErro))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrMasc)
                        .addGap(8, 8, 8)
                        .addComponent(jrFemi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlSexoErro))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlIdadeErro))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlSaffari)
                                .addGap(18, 18, 18)
                                .addComponent(jrSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrNao))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jlCapturado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtCapturado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPokemonsErro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlInsignia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrAlma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrTerra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrTrovao)
                                .addGap(2, 2, 2)
                                .addComponent(jrCascata))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrLama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrArcoIris)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrRocha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrVulcao)))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexo)
                    .addComponent(jrMasc)
                    .addComponent(jrFemi)
                    .addComponent(jlSexoErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdade)
                    .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIdadeErro))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCidade)
                    .addComponent(jrPallet)
                    .addComponent(jrViridian)
                    .addComponent(jrPewter)
                    .addComponent(jrVermilion)
                    .addComponent(jrLavender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrSaffron)
                    .addComponent(jrFuchsia)
                    .addComponent(jrCinnabar)
                    .addComponent(jrCerulean)
                    .addComponent(jrCeladon))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrLama)
                            .addComponent(jrArcoIris)
                            .addComponent(jrRocha)
                            .addComponent(jrVulcao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrAlma)
                            .addComponent(jrTerra)
                            .addComponent(jrTrovao)
                            .addComponent(jrCascata))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlInsignia)
                        .addGap(24, 24, 24)))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPokemonsErro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCapturado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCapturado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 11, Short.MAX_VALUE)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSaffari)
                    .addComponent(jrSim)
                    .addComponent(jrNao))
                .addContainerGap())
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirmar Cadastro"));

        jbCadastrar.setText("Cadastrar Personagem");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpAcoes)
                    .addComponent(jlpDados))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cadastrar() {
        try {
            PersonagemVO pCA = new PersonagemVO();
            pCA.setNome(jtNome.getText());
            pCA.setSexo(bgSexo.getSelection().getActionCommand());
            pCA.setIdade(Integer.parseInt(jtIdade.getText()));
            pCA.setPokemonsCapturado(Integer.parseInt(jtCapturado.getText()));
            pCA.setCidade(bgCidade.getSelection().getActionCommand());
            pCA.setInsignia(bgInsig.getSelection().getActionCommand());
            pCA.setSaffari(bgSimNao.getSelection().getActionCommand());
            
          
            //Enviando objeto pVO para ser persistido no banco de dados
            PersonagemServicos ps = servicos.ServicosFactory.getPersonagemServicos();
            ps.cadastrarPersonagem(pCA);

            //Mensagem de sucesso!
            JOptionPane.showMessageDialog(this,
                    "Personagem cadastrado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERRO! " + e.getMessage());
        }//fecha catch
    }//fecha método

    private void limpar() {
        jtNome.setText("");
        jtIdade.setText("");
        jtCapturado.setText("");
       

        //Limpando os RadioButton
        bgCidade.clearSelection();
        bgSexo.clearSelection();
        bgSimNao.clearSelection();
        bgCidade.clearSelection();
    }//fecha método     
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
        jtNome.grabFocus();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
        jtNome.grabFocus();

    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        if (jtNome.getText().isEmpty()
                || jtNome.getText().length() < 1
                || jtNome.getText().length() > 30) {

            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));

        } else {

            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/certo.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtIdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtIdadeFocusLost
        if (jtIdade.getText().isEmpty()
                || jtIdade.getText().length() < 1
                || jtIdade.getText().length() > 30) {

            jlIdadeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));

        } else {

            jlIdadeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/certo.png")));
        }
    }//GEN-LAST:event_jtIdadeFocusLost

    private void jtCapturadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCapturadoFocusLost
        if (jtCapturado.getText().isEmpty()
                || jtCapturado.getText().length() < 1
                || jtNome.getText().length() > 30) {

            jlPokemonsErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));

        } else {

            jlPokemonsErro.setIcon(new ImageIcon(getClass().getResource("/imagens/certo.png")));
        }
    }//GEN-LAST:event_jtCapturadoFocusLost

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrMasc.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jrMascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMascKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtIdade.grabFocus();
        }
    }//GEN-LAST:event_jrMascKeyPressed

    private void jrFemiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtIdade.grabFocus();
        }
    }//GEN-LAST:event_jrFemiKeyPressed

    private void jtIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrPallet.grabFocus();
        }
    }//GEN-LAST:event_jtIdadeKeyPressed

    private void jrPalletKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrPalletKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrPalletKeyPressed

    private void jrViridianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrViridianKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrViridianKeyPressed

    private void jrPewterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrPewterKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrPewterKeyPressed

    private void jrVermilionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrVermilionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrVermilionKeyPressed

    private void jrLavenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrLavenderKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrLavenderKeyPressed

    private void jrSaffronKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSaffronKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrSaffronKeyPressed

    private void jrCinnabarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCinnabarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrCinnabarKeyPressed

    private void jrCeruleanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCeruleanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrCeruleanKeyPressed

    private void jrCeladonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCeladonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrAlma.grabFocus();
        }
    }//GEN-LAST:event_jrCeladonKeyPressed

    private void jtCapturadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCapturadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrSim.grabFocus();
        }
    }//GEN-LAST:event_jtCapturadoKeyPressed

    private void jrSimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSimKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
            jtNome.grabFocus();

        }
    }//GEN-LAST:event_jrSimKeyPressed

    private void jrNaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrNaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
            jtNome.grabFocus();
    }//GEN-LAST:event_jrNaoKeyPressed
 }
    
    private void jrLamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrLamaKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCapturado.grabFocus();
        }
    }//GEN-LAST:event_jrLamaKeyPressed

    private void jrArcoIrisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrArcoIrisKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCapturado.grabFocus();
        }
    }//GEN-LAST:event_jrArcoIrisKeyPressed

    private void jrRochaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrRochaKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCapturado.grabFocus();
        }
    }//GEN-LAST:event_jrRochaKeyPressed

    private void jrVulcaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrVulcaoKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCapturado.grabFocus();
        }
    }//GEN-LAST:event_jrVulcaoKeyPressed

    private void jrAlmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrAlmaKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCapturado.grabFocus();
        }
    }//GEN-LAST:event_jrAlmaKeyPressed

    private void jrTerraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrTerraKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCapturado.grabFocus();
        }
    }//GEN-LAST:event_jrTerraKeyPressed

    private void jrTrovaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrTrovaoKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCapturado.grabFocus();
        }
    }//GEN-LAST:event_jrTrovaoKeyPressed

    private void jrCascataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCascataKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCapturado.grabFocus();
        }
    }//GEN-LAST:event_jrCascataKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCidade;
    private javax.swing.ButtonGroup bgInsig;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.ButtonGroup bgSimNao;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCapturado;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlIdadeErro;
    private javax.swing.JLabel jlInsignia;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlPokemonsErro;
    private javax.swing.JLabel jlSaffari;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlSexoErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrAlma;
    private javax.swing.JRadioButton jrArcoIris;
    private javax.swing.JRadioButton jrCascata;
    private javax.swing.JRadioButton jrCeladon;
    private javax.swing.JRadioButton jrCerulean;
    private javax.swing.JRadioButton jrCinnabar;
    private javax.swing.JRadioButton jrFemi;
    private javax.swing.JRadioButton jrFuchsia;
    private javax.swing.JRadioButton jrLama;
    private javax.swing.JRadioButton jrLavender;
    private javax.swing.JRadioButton jrMasc;
    private javax.swing.JRadioButton jrNao;
    private javax.swing.JRadioButton jrPallet;
    private javax.swing.JRadioButton jrPewter;
    private javax.swing.JRadioButton jrRocha;
    private javax.swing.JRadioButton jrSaffron;
    private javax.swing.JRadioButton jrSim;
    private javax.swing.JRadioButton jrTerra;
    private javax.swing.JRadioButton jrTrovao;
    private javax.swing.JRadioButton jrVermilion;
    private javax.swing.JRadioButton jrViridian;
    private javax.swing.JRadioButton jrVulcao;
    private javax.swing.JTextField jtCapturado;
    private javax.swing.JTextField jtIdade;
    private javax.swing.JTextField jtNome;
    // End of variables declaration//GEN-END:variables
}