package visao;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.PokemonVO;
import servicos.PokemonsServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Douglas
 * @since 07/07/2018 - 3:46
 * @version 1.0 - Beta Carrero
 */
public class GuiCadPokemon extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCadPessoa
     */
    public GuiCadPokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPokeball = new javax.swing.ButtonGroup();
        bgTipo = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlPokemon = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jlNivel = new javax.swing.JLabel();
        jlPokebola = new javax.swing.JLabel();
        jtPokemon = new javax.swing.JTextField();
        jtNivel = new javax.swing.JTextField();
        jrPokeBall = new javax.swing.JRadioButton();
        jrGreatBall = new javax.swing.JRadioButton();
        jrSuperBall = new javax.swing.JRadioButton();
        jrMasterBall = new javax.swing.JRadioButton();
        jrUltraBall = new javax.swing.JRadioButton();
        jrSaffariBall = new javax.swing.JRadioButton();
        jlPedra = new javax.swing.JLabel();
        jtPedra = new javax.swing.JTextField();
        jlPokemonErro = new javax.swing.JLabel();
        jlNivelErro = new javax.swing.JLabel();
        jlPedraErro = new javax.swing.JLabel();
        jrFogo = new javax.swing.JRadioButton();
        jrGelo = new javax.swing.JRadioButton();
        jrAgua = new javax.swing.JRadioButton();
        jrRaio = new javax.swing.JRadioButton();
        jrPedra = new javax.swing.JRadioButton();
        jrTerra = new javax.swing.JRadioButton();
        jrFantasma = new javax.swing.JRadioButton();
        jrNormal = new javax.swing.JRadioButton();
        jrLutador = new javax.swing.JRadioButton();
        jrVenenoso = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jrVoador = new javax.swing.JRadioButton();
        jrPsi = new javax.swing.JRadioButton();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JToggleButton();
        jbLimpar = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jlpDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Pokemon"));
        jlpDados.setToolTipText("");

        jlPokemon.setText("Pokemon:");

        jlTipo.setText("Tipo Pokemon:");

        jlNivel.setText("Nível Pokemon:");

        jlPokebola.setText("Pokebola Usada:");

        jtPokemon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPokemonFocusLost(evt);
            }
        });
        jtPokemon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPokemonKeyPressed(evt);
            }
        });

        jtNivel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNivelFocusLost(evt);
            }
        });
        jtNivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNivelKeyPressed(evt);
            }
        });

        bgPokeball.add(jrPokeBall);
        jrPokeBall.setText("Poke Ball");
        jrPokeBall.setActionCommand("PokeBall" );
        jrPokeBall.setInheritsPopupMenu(true);
        jrPokeBall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrPokeBallKeyPressed(evt);
            }
        });

        bgPokeball.add(jrGreatBall);
        jrGreatBall.setText("Great Ball");
        jrGreatBall.setActionCommand("GreatBall");
        jrGreatBall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrGreatBallKeyPressed(evt);
            }
        });

        bgPokeball.add(jrSuperBall);
        jrSuperBall.setText("Super Ball");
        jrSuperBall.setActionCommand("SuperBall");
        jrSuperBall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSuperBallKeyPressed(evt);
            }
        });

        bgPokeball.add(jrMasterBall);
        jrMasterBall.setText("Master Ball");
        jrMasterBall.setActionCommand("MasterBall");
        jrMasterBall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMasterBallKeyPressed(evt);
            }
        });

        bgPokeball.add(jrUltraBall);
        jrUltraBall.setText("Ultra Ball");
        jrUltraBall.setActionCommand("UltraBall");
        jrUltraBall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrUltraBallKeyPressed(evt);
            }
        });

        bgPokeball.add(jrSaffariBall);
        jrSaffariBall.setText("Saffari Ball");
        jrSaffariBall.setActionCommand("SaffariBall");
        jrSaffariBall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSaffariBallKeyPressed(evt);
            }
        });

        jlPedra.setText("Pedra Evolutiva:");

        jtPedra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPedraFocusLost(evt);
            }
        });
        jtPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPedraActionPerformed(evt);
            }
        });
        jtPedra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPedraKeyPressed(evt);
            }
        });

        bgTipo.add(jrFogo);
        jrFogo.setText("Fogo");
        jrFogo.setActionCommand("Fogo");

        bgTipo.add(jrGelo);
        jrGelo.setText("Gelo");
        jrGelo.setActionCommand("Gelo");

        bgTipo.add(jrAgua);
        jrAgua.setText("Água");
        jrAgua.setActionCommand("Agua");

        bgTipo.add(jrRaio);
        jrRaio.setText("Raio");
        jrRaio.setActionCommand("Raio");

        bgTipo.add(jrPedra);
        jrPedra.setText("Pedra");
        jrPedra.setActionCommand("Pedra");

        bgTipo.add(jrTerra);
        jrTerra.setText("Terra");
        jrTerra.setActionCommand("Terra");

        bgTipo.add(jrFantasma);
        jrFantasma.setText("Fantasma");
        jrFantasma.setActionCommand("Fantasma");

        bgTipo.add(jrNormal);
        jrNormal.setText("Normal");
        jrNormal.setActionCommand("Normal");

        bgTipo.add(jrLutador);
        jrLutador.setText("Lutador");
        jrLutador.setActionCommand("Lutador");

        bgTipo.add(jrVenenoso);
        jrVenenoso.setText("Venenoso");
        jrVenenoso.setActionCommand("Venenoso");

        bgTipo.add(jRadioButton1);
        jRadioButton1.setText("Dragão");
        jRadioButton1.setActionCommand("Dragão");

        bgTipo.add(jRadioButton2);
        jRadioButton2.setText("Grama");
        jRadioButton2.setActionCommand("Grama");

        bgTipo.add(jrVoador);
        jrVoador.setText("Voador");
        jrVoador.setActionCommand("Voador");

        bgTipo.add(jrPsi);
        jrPsi.setText("Psíquico");
        jrPsi.setActionCommand("Psíquico");

        jlpDados.setLayer(jlPokemon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNivel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPokebola, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtPokemon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNivel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrPokeBall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrGreatBall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSuperBall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrMasterBall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrUltraBall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSaffariBall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPedra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtPedra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPokemonErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNivelErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPedraErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrFogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrGelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrAgua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrRaio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrPedra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrTerra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrFantasma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrNormal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrLutador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrVenenoso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrVoador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrPsi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNivel)
                            .addComponent(jlPokemon))
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jtPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPokemonErro))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNivelErro))))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlPokebola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrPokeBall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrGreatBall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrSuperBall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrUltraBall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrMasterBall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrSaffariBall))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jrGelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrRaio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrTerra))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrFogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrAgua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrPedra)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrFantasma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrLutador))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jrNormal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrVenenoso)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrPsi))
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrVoador))))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlPedra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPedraErro)))
                .addGap(32, 32, 32))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPokemon)
                    .addComponent(jtPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPokemonErro))
                .addGap(9, 9, 9)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNivel)
                    .addComponent(jtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNivelErro))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPokebola)
                    .addComponent(jrPokeBall)
                    .addComponent(jrGreatBall)
                    .addComponent(jrSuperBall)
                    .addComponent(jrUltraBall)
                    .addComponent(jrMasterBall)
                    .addComponent(jrSaffariBall))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipo)
                    .addComponent(jrFogo)
                    .addComponent(jrAgua)
                    .addComponent(jrPedra)
                    .addComponent(jrFantasma)
                    .addComponent(jrLutador)
                    .addComponent(jRadioButton1)
                    .addComponent(jrVoador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrRaio)
                    .addComponent(jrGelo)
                    .addComponent(jrTerra)
                    .addComponent(jrNormal)
                    .addComponent(jrVenenoso)
                    .addComponent(jRadioButton2)
                    .addComponent(jrPsi))
                .addGap(17, 17, 17)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPedra)
                    .addComponent(jtPedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPedraErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Pokemon"));

        jbCadastrar.setText("Cadastrar Pokemon");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpAcoes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cadastrar() {
        try {
            PokemonVO e = new PokemonVO();
            e.setPokemon(jtPokemon.getText());
            e.setLvlPokemon(Integer.parseInt(jtNivel.getText()));
            e.setPedraPokemon(jtPedra.getText());
            e.setTipoPokemon(bgTipo.getSelection().getActionCommand());           
            e.setPokebolaUsada(bgPokeball.getSelection().getActionCommand());

            
            
            //Enviando objeto pVO para ser persistido no banco de dados
            PokemonsServicos ps = ServicosFactory.getPokemonsServicos();
            ps.cadastrarPokemon(e);

            //Mensagem de sucesso!
            JOptionPane.showMessageDialog(this,
                    "Pokemon cadastrado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "ERRouuuuuuuuuuuuu! " + e.getMessage());
        }//fecha catch
    }//fecha método

    private void limpar() {
        jtNivel.setText("");
        jtPedra.setText("");
        jtPokemon.setText("");

    

        //Limpando os RadioButton
        bgPokeball.clearSelection();
        bgTipo.clearSelection();
    }//fecha método

    private void jtPokemonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPokemonFocusLost
        if (jtPokemon.getText().isEmpty()
                || jtPokemon.getText().length() < 1
                || jtNivel.getText().length() > 30) {

            jlPokemonErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));

        } else {

            jlPokemonErro.setIcon(new ImageIcon(getClass().getResource("/imagens/certo.png")));
        }
    }//GEN-LAST:event_jtPokemonFocusLost

    private void jtNivelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNivelFocusLost
        if (jtNivel.getText().isEmpty()
                || jtNivel.getText().length() < 1
                || jtNivel.getText().length() > 30) {

            jlNivelErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));

        } else {

            jlNivelErro.setIcon(new ImageIcon(getClass().getResource("/imagens/certo.png")));
        }
    }//GEN-LAST:event_jtNivelFocusLost

    private void jtPedraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPedraFocusLost
        if (jtPedra.getText().isEmpty()
                || jtPedra.getText().length() < 1
                || jtPedra.getText().length() > 30) {

            jlPedraErro.setIcon(new ImageIcon(getClass().getResource("/imagens/erro.png")));

        } else {

            jlPedraErro.setIcon(new ImageIcon(getClass().getResource("/imagens/certo.png")));
        }
    }//GEN-LAST:event_jtPedraFocusLost

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        jtPokemon.grabFocus();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
        jtPokemon.grabFocus();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtPokemonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPokemonKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtNivel.grabFocus();
        }
    }//GEN-LAST:event_jtPokemonKeyPressed

    private void jtNivelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNivelKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrPokeBall.grabFocus();
        }
    }//GEN-LAST:event_jtNivelKeyPressed

    private void jrPokeBallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrPokeBallKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             jrFogo.grabFocus();
          
        }
    }//GEN-LAST:event_jrPokeBallKeyPressed

    private void jrGreatBallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrGreatBallKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
              jrFogo.grabFocus();
        }
    }//GEN-LAST:event_jrGreatBallKeyPressed

    private void jrSuperBallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSuperBallKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           jrFogo.grabFocus();
        }
    }//GEN-LAST:event_jrSuperBallKeyPressed

    private void jrUltraBallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrUltraBallKeyPressed
          if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrFogo.grabFocus();
        }
    }//GEN-LAST:event_jrUltraBallKeyPressed

    private void jrMasterBallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMasterBallKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           jrFogo.grabFocus();
        }
    }//GEN-LAST:event_jrMasterBallKeyPressed

    private void jrSaffariBallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSaffariBallKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrFogo.grabFocus();
        }
    }//GEN-LAST:event_jrSaffariBallKeyPressed

    private void jtPedraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPedraKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }
    }//GEN-LAST:event_jtPedraKeyPressed

    private void jtPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPedraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPedraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPokeball;
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JToggleButton jbCadastrar;
    private javax.swing.JToggleButton jbLimpar;
    private javax.swing.JLabel jlNivel;
    private javax.swing.JLabel jlNivelErro;
    private javax.swing.JLabel jlPedra;
    private javax.swing.JLabel jlPedraErro;
    private javax.swing.JLabel jlPokebola;
    private javax.swing.JLabel jlPokemon;
    private javax.swing.JLabel jlPokemonErro;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrAgua;
    private javax.swing.JRadioButton jrFantasma;
    private javax.swing.JRadioButton jrFogo;
    private javax.swing.JRadioButton jrGelo;
    private javax.swing.JRadioButton jrGreatBall;
    private javax.swing.JRadioButton jrLutador;
    private javax.swing.JRadioButton jrMasterBall;
    private javax.swing.JRadioButton jrNormal;
    private javax.swing.JRadioButton jrPedra;
    private javax.swing.JRadioButton jrPokeBall;
    private javax.swing.JRadioButton jrPsi;
    private javax.swing.JRadioButton jrRaio;
    private javax.swing.JRadioButton jrSaffariBall;
    private javax.swing.JRadioButton jrSuperBall;
    private javax.swing.JRadioButton jrTerra;
    private javax.swing.JRadioButton jrUltraBall;
    private javax.swing.JRadioButton jrVenenoso;
    private javax.swing.JRadioButton jrVoador;
    private javax.swing.JTextField jtNivel;
    private javax.swing.JTextField jtPedra;
    private javax.swing.JTextField jtPokemon;
    // End of variables declaration//GEN-END:variables
}
