package visao;

import javax.swing.UIManager;

/**
 *
 * @author Douglas
 * @since 07/07/2018 - 3:46
 * @version 1.0 - Beta Carrero
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadPersonagem = new javax.swing.JMenuItem();
        jmiCadPokemon = new javax.swing.JMenuItem();
        jmManu = new javax.swing.JMenu();
        jmiManPersonagem = new javax.swing.JMenuItem();
        jmiManPokemon = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        jmCadastro.setText("Cadastro");

        jmiCadPersonagem.setText("Personagem");
        jmiCadPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadPersonagemActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadPersonagem);

        jmiCadPokemon.setText("Pokemon");
        jmiCadPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadPokemonActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadPokemon);

        jMenuBar1.add(jmCadastro);

        jmManu.setText("Manutenção");

        jmiManPersonagem.setText("Personagem");
        jmiManPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManPersonagemActionPerformed(evt);
            }
        });
        jmManu.add(jmiManPersonagem);

        jmiManPokemon.setText("Pokemon");
        jmiManPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManPokemonActionPerformed(evt);
            }
        });
        jmManu.add(jmiManPokemon);

        jMenuBar1.add(jmManu);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadPersonagemActionPerformed
        // TODO add your handling code here:
        abrirCadPersonagem();
    }//GEN-LAST:event_jmiCadPersonagemActionPerformed

    private void jmiCadPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadPokemonActionPerformed
        // TODO add your handling code here:
        abrirCadPokemon();
    }//GEN-LAST:event_jmiCadPokemonActionPerformed

    private void jmiManPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManPersonagemActionPerformed
        abrirManutencaoPersonagem();
    }//GEN-LAST:event_jmiManPersonagemActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
       System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmiManPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManPokemonActionPerformed
        abrirManutencaoPokemon();
    }//GEN-LAST:event_jmiManPokemonActionPerformed
    private void abrirCadPersonagem() {
        GuiCadPersonagem gce = new GuiCadPersonagem();
        jAreaTrabalho.add(gce);
        gce.setVisible(true);
    }//fecha método

    private void abrirCadPokemon() {
        GuiCadPokemon gcs = new GuiCadPokemon();
        jAreaTrabalho.add(gcs);
        gcs.setVisible(true);
    }//fecha método

    private void abrirManutencaoPersonagem() {
        GuiManutencaoPersonagem gcs = new GuiManutencaoPersonagem();
        jAreaTrabalho.add(gcs);
        gcs.setVisible(true);
    }//fecha método
    private void abrirManutencaoPokemon() {
        GuiManutencaoPokemon gcs = new GuiManutencaoPokemon();
        jAreaTrabalho.add(gcs);
        gcs.setVisible(true);
    }//fecha método
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
            com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManu;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadPersonagem;
    private javax.swing.JMenuItem jmiCadPokemon;
    private javax.swing.JMenuItem jmiManPersonagem;
    private javax.swing.JMenuItem jmiManPokemon;
    // End of variables declaration//GEN-END:variables
}
